apiVersion: v1
kind: Service
metadata:
  name: bmi-webapp-1
spec:
  ports:
  - name: "flow2"
    port: 8888
    targetPort: 8888
    nodePort: 8998
    protocol: TCP
  type: NodePort
  selector:
    name: bmi-webapp-1