uri: cncf/demo-for-cncf-ci/build-test-release-deploy
title: Demo For Cloud Native Computing Foundation CI Working Group
version: 4
tag: latest
timeout: 0
#receivers:
#  -
#    type: mail
#    address: wangqilin@containerops.sh
stages:
  -
    type: start
    name: start
    title: Start
  -
    type: normal
    name: servicecomb-bmi-checkstyle
    title: Building, testing bmi project.
    sequencing: sequence
    actions:
      -
        name: checkstyle-bmi
        title: Checktyle of bmi
        jobs:
          -
            type: component
            endpoint: 10.229.40.121:8082/system/analysis-java-gradle-checkstyle:latest
            resources:
              cpu: 2
              memory: 4G
            timeout: 0
            environments:
              - CO_DATA: "version=gradle4 git-url=https://github.com/MabinGo/bmi.git out-put-type=json report-path=./webapp/build/reports/checkstyle"
      -
        name: build-bmi
        title: Build bmi image by assembling
        jobs:
          -
            type: component
            endpoint: 10.229.40.121:8082/system/call-assembling-manven:v0.6
            resources:
              cpu: 1
              memory: 1G
            timeout: 0
            environments:
              - CO_DATA: "git-url=https://github.com/MabinGo/bmi.git assembling-url=https://10.229.40.121:8083 registry-url=10.229.40.121:8082 namespace=servicecomb image=bmi tag=latest insecure-registry=10.229.40.121:8082"
      -
        name: deploy-bmi
        title: Deploy bmi
        jobs:
          -
            name: bmi-calculator
            type: component
            endpoint: 10.229.40.121:8082/system/create-deployment:latest
            resources:
              cpu: 1
              memory: 1G
            environments:
              - CO_DATA: "api-server-url=http://10.229.49.97:8080"
              - YAML: "YXBpVmVyc2lvbjogZXh0ZW5zaW9ucy92MWJldGExCmtpbmQ6IERlcGxveW1lbnQKbWV0YWRhdGE6CiAgbmFtZTogYm1pLWNhbGN1bGF0b3ItMQpzcGVjOgogIHJlcGxpY2FzOiAxCiAgdGVtcGxhdGU6CiAgICBtZXRhZGF0YToKICAgICAgbGFiZWxzOgogICAgICAgIG5hbWU6IGJtaS1jYWxjdWxhdG9yLTEKICAgIHNwZWM6CiAgICAgIGNvbnRhaW5lcnM6CiAgICAgIC0gZW52OgogICAgICAgIC0gbmFtZTogSkFWQV9PUFRTCiAgICAgICAgICB2YWx1ZTogLURjc2Uuc2VydmljZS5yZWdpc3RyeS5hZGRyZXNzPWh0dHA6Ly8xMC4yMjkuNDUuMTUyOjMwMTAxCiAgICAgICAgLSBuYW1lOiBKQVJfTkFNRQogICAgICAgICAgdmFsdWU6IGNhbGN1bGF0b3ItMC40LjAtU05BUFNIT1QKICAgICAgICBpbWFnZTogMTAuMjI5LjQwLjEyMTo4MDgyL3NlcnZpY2Vjb21iL2JtaTpsYXRlc3QKICAgICAgICBuYW1lOiBibWktY2FsY3VsYXRvci0x"
          -
            name: bmi-webapp-service
            type: component
            endpoint: 10.229.40.121:8082/system/create-service:latest
            resources:
              cpu: 1
              memory: 1G
            environments:
              - CO_DATA: "api-server-url=http://10.229.49.97:8080"
              - YAML: "YXBpVmVyc2lvbjogdjEKa2luZDogU2VydmljZQptZXRhZGF0YToKICBuYW1lOiBibWktd2ViYXBwLTEKc3BlYzoKICBwb3J0czoKICAtIG5hbWU6ICJmbG93MiIKICAgIHBvcnQ6IDg4ODgKICAgIHRhcmdldFBvcnQ6IDg4ODgKICAgIG5vZGVQb3J0OiA4OTk4CiAgICBwcm90b2NvbDogVENQCiAgdHlwZTogTm9kZVBvcnQKICBzZWxlY3RvcjoKICAgIG5hbWU6IGJtaS13ZWJhcHAtMQ=="
          -
            name: bmi-webapp
            type: component
            endpoint: 10.229.40.121:8082/system/create-deployment:latest
            resources:
              cpu: 1
              memory: 1G
            environments:
              - CO_DATA: "api-server-url=http://10.229.49.97:8080"
              - YAML: "YXBpVmVyc2lvbjogZXh0ZW5zaW9ucy92MWJldGExCmtpbmQ6IERlcGxveW1lbnQKbWV0YWRhdGE6CiAgbmFtZTogYm1pLXdlYmFwcC0xCnNwZWM6CiAgcmVwbGljYXM6IDEKICB0ZW1wbGF0ZToKICAgIG1ldGFkYXRhOgogICAgICBsYWJlbHM6CiAgICAgICAgbmFtZTogYm1pLXdlYmFwcC0xCiAgICBzcGVjOgogICAgICBjb250YWluZXJzOgogICAgICAtIGVudjoKICAgICAgICAtIG5hbWU6IEpBVkFfT1BUUwogICAgICAgICAgdmFsdWU6IC1EY3NlLnNlcnZpY2UucmVnaXN0cnkuYWRkcmVzcz1odHRwOi8vMTAuMjI5LjQ1LjE1MjozMDEwMQogICAgICAgIC0gbmFtZTogSkFSX05BTUUKICAgICAgICAgIHZhbHVlOiB3ZWJhcHAtMC40LjAtU05BUFNIT1QKICAgICAgICBpbWFnZTogMTAuMjI5LjQwLjEyMTo4MDgyL3NlcnZpY2Vjb21iL2JtaTpsYXRlc3QKICAgICAgICBuYW1lOiBibWktd2ViYXBwLTEKICAgICAgICBwb3J0czoKICAgICAgICAtIGNvbnRhaW5lclBvcnQ6IDg4ODg="
      -
        name: system-test-bmi
        title: system test of bmi
        jobs:
          -
            type: component
            endpoint: 10.229.40.121:8082/servicecomb/bmi:latest
            resources:
              cpu: 1
              memory: 1G
            environments:
              - JAVA_OPTS: "-Dwebserver.address=http://10.229.49.97:8998"
              - JAR_NAME: "system-tests-0.4.0-SNAPSHOT"
#      -
#        name: release-bmi
#        title: release bmi image to huawei cloud
#        jobs:
#          -
#            type: component
#            endpoint: 10.229.40.121:8082/system/call-assembling-manven:v0.5
#            resources:
#              cpu: 1
#              memory: 1G
#            timeout: 0
#            environments:
#              - CO_DATA: "git-url=https://github.com/MabinGo/bmi.git assembling-url=https://10.229.40.121:8083 registry-url=registry.cn-north-1.huaweicloud.com namespace=liuguo image=bmi tag=latest authstr=ewoJInVzZXJuYW1lIjogImNuLW5vcnRoLTFASERFV1lNRFQ5Q1VGRExETDVYVEwiLAoJInBhc3N3b3JkIjogImI5MzQwODM5MzllYjNkMDI4YjI2OWE0ZTU1OGQ4NmFhZjIyNWIxNTQ3NGI0NzY1ZWQ3Mjc4ZWZlN2NhYTA4ZDkiCn0K insecure-registry=10.229.40.121:8082"
  -
    type: end
    name: end
    title: End
    
